package com.bipin080.ecofood

import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import app.cash.turbine.test
import com.bipin080.ecofood.data.SavedRecipeDao
import com.bipin080.ecofood.data.SavedRecipeDatabase
import com.bipin080.ecofood.data.SavedRecipeEntity
import com.google.common.truth.Truth.assertThat
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class SavedRecipeDatabaseTest {

    private lateinit var db: SavedRecipeDatabase
    private lateinit var dao: SavedRecipeDao

    @Before
    fun setup() {
        db = Room.inMemoryDatabaseBuilder(
            ApplicationProvider.getApplicationContext(),
            SavedRecipeDatabase::class.java
        ).allowMainThreadQueries().build()

        dao = db.savedRecipeDao()
    }

    @After
    fun teardown() {
        db.close()
    }

    @Test
    fun insert_and_read_recipe() = runTest {
        val recipe = SavedRecipeEntity(
            title = "Pasta",
            description = "Tasty",
            cookingTime = "20 min",
            servings = "2",
            wasteReduction = "High",
            calories = "500",
            ingredientsJson = "[]"
        )

        dao.insert(recipe)

        dao.getAll().test {
            val list = awaitItem()
            assertThat(list.size).isEqualTo(1)
            assertThat(list[0].title).isEqualTo("Pasta")
        }
    }

    @Test
    fun delete_recipe() = runTest {
        val recipe = SavedRecipeEntity(
            title = "Curry",
            description = "Spicy",
            cookingTime = "30 min",
            servings = "4",
            wasteReduction = "Medium",
            calories = "600",
            ingredientsJson = "[]"
        )

        dao.insert(recipe)

        // fetch item with autogenerated ID
        val itemFromDb = dao.getAll().first().first()

        dao.delete(itemFromDb)

        dao.getAll().test {
            val list = awaitItem()
            assertThat(list).isEmpty()
        }
    }


    @Test
    fun delete_recipe_by_title_and_description() = runTest {
        val recipe = SavedRecipeEntity(
            title = "Toast",
            description = "Simple",
            cookingTime = "5 min",
            servings = "1",
            wasteReduction = "Low",
            calories = "200",
            ingredientsJson = "[]"
        )

        dao.insert(recipe)
        dao.deleteByTitleAndDescription("Toast", "Simple")

        dao.getAll().test {
            val list = awaitItem()
            assertThat(list).isEmpty()
        }
    }

    @Test
    fun clear_all_recipes() = runTest {
        val recipe1 = SavedRecipeEntity(
            title = "A",
            description = "D1",
            cookingTime = "10",
            servings = "1",
            wasteReduction = "Low",
            calories = "100",
            ingredientsJson = "[]"
        )

        val recipe2 = SavedRecipeEntity(
            title = "B",
            description = "D2",
            cookingTime = "20",
            servings = "2",
            wasteReduction = "Medium",
            calories = "200",
            ingredientsJson = "[]"
        )

        dao.insert(recipe1)
        dao.insert(recipe2)

        dao.clear()

        dao.getAll().test {
            val list = awaitItem()
            assertThat(list).isEmpty()
        }
    }
}
